version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    groups:
      uv-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      uv-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    groups:
      docker-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      docker-major:
        patterns:
          - "*"
        update-types:
          - "major"
