FROM python:3.11-slim

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PIP_NO_CACHE_DIR=off

WORKDIR /usr/src/bbot

RUN apt-get update && apt-get install -y \
    openssl \
    gcc \
    g++ \
    git \
    make \
    pkg-config \
    zlib1g-dev \
    unzip \
    curl \
    wget \
    vim \
    nano \
    sudo

COPY . .

RUN pip install .

RUN bbot --install-all-deps

WORKDIR /root

ENTRYPOINT [ "bbot" ]
