# Generated by Django 4.0.3 on 2022-03-29 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('domain', 'DOMAIN'), ('ip', 'IP'), ('port', 'PORT'), ('url', 'URL')], max_length=32)),
                ('data', models.CharField(max_length=1024)),
                ('module', models.CharField(max_length=256)),
                ('source', models.ManyToManyField(to='api.event')),
            ],
        ),
    ]
