# Generated by Django 4.0.3 on 2022-03-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.ManyToManyField(blank=True, to='api.event'),
        ),
    ]
