# Generated by Django 4.0.3 on 2022-03-30 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.ManyToManyField(blank=True, through='api.EventRelationship', to='api.event'),
        ),
        migrations.AddField(
            model_name='eventrelationship',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_events', to='api.event'),
        ),
        migrations.AddField(
            model_name='eventrelationship',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_events', to='api.event'),
        ),
    ]
