# Generated by Django 4.0.3 on 2022-03-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_eventrelationship_alter_event_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='source',
        ),
    ]
