# Generated by Django 4.0.3 on 2022-03-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_event_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.ManyToManyField(blank=True, through='api.EventRelationship', to='api.event'),
        ),
    ]
