flag_descriptions = {
    "active": "Makes active connections to target systems",
    "affiliates": "Discovers affiliated hostnames/domains",
    "baddns": "Runs all modules from the DNS auditing tool BadDNS",
    "cloud-enum": "Enumerates cloud resources",
    "code-enum": "Find public code repositories and search them for secrets etc.",
    "download": "Modules that download files, apps, or repositories",
    "email-enum": "Enumerates email addresses",
    "iis-shortnames": "Scans for IIS Shortname vulnerability",
    "invasive": "Intrusive or potentially destructive",
    "loud": "Generates a large amount of network traffic",
    "passive": "Never connects to target systems",
    "safe": "Non-intrusive and non-destructive",
    "portscan": "Discovers open ports",
    "report": "Generates a report at the end of the scan",
    "service-enum": "Identifies protocols running on open ports",
    "slow": "May take a long time to complete",
    "social-enum": "Enumerates social media",
    "subdomain-enum": "Enumerates subdomains",
    "subdomain-hijack": "Detects hijackable subdomains",
    "web": "Non-intrusive web scan functionality",
    "web-heavy": "More advanced web scanning functionality",
    "web-paramminer": "Discovers HTTP parameters through brute-force",
    "web-screenshots": "Takes screenshots of web pages",
}
