flag_descriptions = {
    "active": "",
    "affiliates": "",
    "aggressive": "",
    "cloud-enum": "",
    "deadly": "",
    "email-enum": "",
    "iis-shortnames": "",
    "passive": "",
    "portscan": "",
    "report": "",
    "safe": "",
    "service-enum": "",
    "slow": "",
    "social-enum": "",
    "subdomain-enum": "",
    "subdomain-hijack": "",
    "web-basic": "",
    "web-paramminer": "",
    "web-screenshots": "",
    "web-thorough": "",
}
