name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  pull-requests: write
  statuses: write

jobs:
  cla:
    uses: blacklanternsecurity/CLA/.github/workflows/cla-reusable.yml@c2df6cfbbc363ce53873ed7e0d3cbb56551a5231 # main
    secrets: inherit
