name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  cla:
    uses: blacklanternsecurity/.github/.github/workflows/cla-reusable.yml@main
    secrets: inherit
