name: Dependabot auto-merge
on: pull_request

permissions: {}

jobs:
  auto-merge:
    permissions:
      contents: write
      pull-requests: write
      checks: read
    uses: blacklanternsecurity/CLA/.github/workflows/dependabot-auto-merge.yml@bd5493d26aab101458d606886d23e62b1354cdba # 2026-10-03
