name: Dependabot auto-merge
on: pull_request

permissions: {}

jobs:
  auto-merge:
    permissions:
      contents: write
      pull-requests: write
      checks: read
    uses: blacklanternsecurity/CLA/.github/workflows/dependabot-auto-merge.yml@40c6e18c0a6e32116eea4f89fc826f53c70889dc # main
