name: Daily Docs Update

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 2:30 AM UTC, a less congested time
  workflow_dispatch:      # Allows manual triggering of the workflow

jobs:
  update_docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          token: ${{ secrets.BBOT_DOCS_UPDATER_PAT }}
          ref: dev  # Checkout the dev branch
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.x"
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
      - name: Install dependencies
        run: uv sync --frozen --group dev
      - name: Generate docs
        run: |
          uv run --no-sync bbot/scripts/docs.py
      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ secrets.BBOT_DOCS_UPDATER_PAT }}
          branch: update-docs
          base: dev
          title: "Automated Docs Update"
          body: "This is an automated pull request to update the documentation."
          committer: blsaccess <info@blacklanternsecurity.com>
          author: blsaccess <info@blacklanternsecurity.com>
